### ISSUE TITLE
500 SERVER ERROR PADA CETAK REKAP DAN LAPORAN REKAP BELUM BAYAR PBB v.22.12.01

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/rilis-pbb#2]
terjadi gagal unduh pada saat mengunduh Rekap Lunas dan Laporan rekap belum bayar PBB di aplikasi PBB v.22.12.01
update tanggal 11 Desember 2022

1. Gagal cetak/unduh Rekap Lunas 
![SERVER ERORR CETAK LAPORAN REKAP LUNAS PBB](https://user-images.githubusercontent.com/59205349/207249234-6b848432-0e97-44c8-be11-79df531276dd.jpg)

2. Gagal cetak/unduh Laporan Rekap Belum Lunas PBB
![SERVER ERORR CETAK REKAP LAPORAN BELUM BAYAR PBB](https://user-images.githubusercontent.com/59205349/207248666-bb3a54ab-b4db-4b86-9da7-54c86598d7f4.jpg)

**Comment by scqolbu24** [comment]
Setelah dicek pada versi terbaru saat ini yaitu v23.02.01 pada issue ini sudah terselesaikan, dapat dicek di https://demopbb.opendesa.id/ username=admin, password=admin

Berikut tangkapan layar:
<img width="960" alt="cetak-rekap1" src="https://user-images.githubusercontent.com/68048807/216538295-8e0c2305-1a90-4a2a-99f6-683c4775e2bd.png">
<img width="960" alt="cetak-rekap2" src="https://user-images.githubusercontent.com/68048807/216538316-73896a74-44e3-448a-aa99-9825b68c7784.png">
<img width="960" alt="cetak-rekap3" src="https://user-images.githubusercontent.com/68048807/216538354-e581df8f-272e-472c-9a5f-be233c3ca95c.png">
<img width="960" alt="cetak-rekap4" src="https://user-images.githubusercontent.com/68048807/216538386-519a1ac1-2cf9-4e37-8493-8b05aa60d78e.png">
<img width="960" alt="cetak-rekap5" src="https://user-images.githubusercontent.com/68048807/216538692-6bd3d9fe-9d60-4f80-9713-c92153b0782d.png">

Dengan demikian issue ini kami tutup, Terimakasih sudah melaporkan.
