### ISSUE TITLE
Tambahkan Kolom Status pada File import sppt.xlxs

### ISSUE THREAD

**Issue by isnantomch** [OpenSID/rilis-pbb#3]
Tambahkan kolom satus (Lunas/Terhutang) pada file import sppt.xlxs supaya memudahkan pada subjek pajak yang sudah lunas. 
![kolom Status pada file sppt](https://user-images.githubusercontent.com/59205349/207251498-659f5839-0c55-41a7-aa4e-c2abd469c134.jpg)

**Comment by scqolbu24** [comment]
Untuk Import sudah dibuat default adalah Terhutang, sehingga pada excel tidak perlu diinput.
Jika diisi Lunas maka pada laporan Rekap Pembayaran tidak dapat ditampilkan, karena tidak ada import ke tabel pembayaran.

**Comment by scqolbu24** [comment]
Issue ini kami tutup, jika ada permintaan lain, silakan dapat dibuatkan issue dan dijelaskan pada issue tersebut. Terimakasih.
